name: needs_delivery
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  background_locator_2: ^2.0.6
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.3
  cherry_toast: ^1.8.0
  connectivity: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.3.4
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  floating_action_bubble: ^1.1.4
  flutter_easyloading: ^3.0.5
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.6
  flutter_secure_storage: ^9.0.0
  flutter_rounded_progress_bar: ^0.3.2
  flutter_local_notifications: ^16.3.0
  go_router: ^13.0.0
  get_it: ^7.6.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  http: ^0.13.3
  maps_launcher: ^2.2.0
  intl: ^0.18.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.6.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  stream_transform: ^2.1.0
  provider: ^6.0.5
  retrofit: '>=4.0.0 <5.0.0'
  rxdart: ^0.27.7
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  url_launcher: ^6.2.4
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  hive_generator: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/app_icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf

  assets:
    - assets/lottie/
    - assets/logo/
    - assets/images/
flutter_intl:
  enabled: true
